In [2]:
import numpy as np
print(np.__version__)
np.show_config()

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/ProgramData/anaconda3/Library/include
    lib directory: C:/ProgramData/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:
  

In [4]:
import numpy as np
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [6]:
import numpy as np
print("original array:\n")
x=np.array([1,2,3,4])
print(x)
print("\n test if none of the elements of the said array is zero:\n")
f=0
for i in range(0,4):
  if x[i]==0:
    f=1
    break
if f==1:
  print("False\n")
else:
  print("True")
  
print("original array:\n")
x=np.array([0,1,2,3])
print(x)
print("\n test if none of the elements of the said array is zero:\n")
t=0
for i in range(0,4):
  if x[i]==0:
    t=1
    break
if t==1:
  print("False\n")  
else:
  print("True")

original array:

[1 2 3 4]

 test if none of the elements of the said array is zero:

True
original array:

[0 1 2 3]

 test if none of the elements of the said array is zero:

False



In [8]:
import numpy as np
print("original array:\n")
x=np.array([1,0,0,0])
print(x)
print("\nTest whether any of the elements of a given array is non-zero: \n")
f=0
for i in range(0,4):
  if x[i]!=0:
    f=1
    break
if f==1:
  print("True\n")
else:
  print("False")
  
print("original array:\n")
x=np.array([0,0,0,0])
print(x)
print("\nTest whether any of the elements of a given array is non-zero:\n")
t=0
for i in range(0,4):
  if x[i]!=0:
    t=1
    break
if t==1:
  print("True\n")  
else:
  print("False")
  
     

original array:

[1 0 0 0]

Test whether any of the elements of a given array is non-zero: 

True

original array:

[0 0 0 0]

Test whether any of the elements of a given array is non-zero:

False


In [10]:
import numpy as np
a = np.array([1, 0, np.nan, np.inf])
print("Original array")
print(a)
print("Test a given array element-wise for finiteness :")
print(np.isfinite(a)) 

Original array
[ 1.  0. nan inf]
Test a given array element-wise for finiteness :
[ True  True False False]


In [12]:
import numpy as np
array = np.array([1, -2, np.inf, -np.inf, 0, 3.5])
pos= np.isposinf(array)
neg = np.isneginf(array)
print("Element-wise positive infinity check:", pos)
print("Element-wise negative infinity check:", neg)

Element-wise positive infinity check: [False False  True False False False]
Element-wise negative infinity check: [False False False  True False False]


In [14]:

import numpy as np
a = np.array([1, 0, np.nan, np.inf])
print("Original array")
print(a)
print("Test element-wise for NaN:")
print(np.isnan(a))

Original array
[ 1.  0. nan inf]
Test element-wise for NaN:
[False False  True False]


In [16]:
import numpy as np
a = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
print("Original array")
print(a)
print("Checking for complex number:")
print(np.iscomplex(a))

print("Checking for real number:")
print(np.isreal(a))

print("Checking for scalar type:")
print(np.isscalar(3.1))

print(np.isscalar([3.1])) 

Original array
[1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]
Checking for complex number:
[ True False False False False  True]
Checking for real number:
[False  True  True  True  True False]
Checking for scalar type:
True
False


In [1]:
import numpy as np
x = np.array([3, 5])
y = np.array([2, 5])
print("Original numbers:")
print(x)
print(y)

print("Comparison - greater")
print(x>y)


print("Comparison - greater_equal")
print(x>=y)


print("Comparison - less")
print(x<y)


print("Comparison - less_equal")
print(x<=y) 

Original numbers:
[3 5]
[2 5]
Comparison - greater
[ True False]
Comparison - greater_equal
[ True  True]
Comparison - less
[False False]
Comparison - less_equal
[False  True]


In [3]:
import numpy as np


x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])


print("Original numbers:")
print(x)
print(y)


print("Comparison - equal:")
print(x==y)


print("Comparison - equal within a tolerance:")
print(np.allclose(x,y,atol=1e-08)) 

Original numbers:
[  72   79   85   90  150 -135  120  -10   60  100]
[  72.         79.         85.         90.        150.       -135.
  120.        -10.         60.        100.000001]
Comparison - equal:
[ True  True  True  True  True  True  True  True  True False]
Comparison - equal within a tolerance:
True


In [5]:
import numpy as np
x= np.array([1, 7, 13, 105])
print("Original array:")
print(x)
print("Size of the memory occupied by the said array:")
print(f"{(x.size*x.itemsize)/8} bytes")

Original array:
[  1   7  13 105]
Size of the memory occupied by the said array:
2.0 bytes


In [7]:
import numpy as np
x=np.zeros(10)
print("An array of 10 zeros:\n")
print(x)
print("\nAn array of 10 ones:\n")
o=np.ones_like(x)
print(o)
print("An array of 10 fives:\n")
print(o*5)

An array of 10 zeros:

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

An array of 10 ones:

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [9]:
import numpy as np
x=np.arange(30,71)
print("Array of the integers from 30 to 70")
print(x) 

Array of the integers from 30 to 70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [11]:
import numpy as np
x=np.arange(30,71,2)
print("Array of the integers from 30 to 70")
print(x) 

Array of the integers from 30 to 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [13]:
import numpy as np
x=np.eye(3)
print('3x3 matrix:')
print(x) 

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
import numpy as np
x=np.random.rand()
print(x)

0.7924848076051827


In [17]:
import numpy as np
x=np.random.rand(15)
print(x)

[0.31235383 0.01845088 0.38302697 0.09669885 0.48585369 0.61818879
 0.39654197 0.27361322 0.17106151 0.84483929 0.97791575 0.6315211
 0.61323055 0.2923369  0.31187516]


In [19]:
import numpy as np
x=np.arange(15,56)
print("original vector:\n")
print(x)
print("values expected first and last value\n")
y=np.delete(x,[0,len(x)-1])
print(y)

original vector:

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
values expected first and last value

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [23]:
import numpy as np
x=np.arange(20,32).reshape(3,4)
print("original vector:\n")
print(x)
print("each element in the array:\n")
y=x.ravel()
for i in range(0,len(y)):
  print(y[i])
  

original vector:

[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
each element in the array:

20
21
22
23
24
25
26
27
28
29
30
31


In [25]:
import numpy as np
x=np.arange(5,51,5)
print("Length 10 with values evenly distributed between 5 and 50:")
print(x)

Length 10 with values evenly distributed between 5 and 50:
[ 5 10 15 20 25 30 35 40 45 50]


In [27]:
import numpy as np
x=np.arange(0,21)
print("Original vector:")
print(x)
print("After changing the sign of the numbers in the range from 9 to 15:")
for i in range(9,16):
  x[i]=x[i]*-1
print(x)    

Original vector:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
After changing the sign of the numbers in the range from 9 to 15:
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [29]:
import numpy as np
print("Vector of length 5 filled with arbitrary integers from 0 to 10:")
x=np.random.randint(0,11,5,'i8')
print(x)

Vector of length 5 filled with arbitrary integers from 0 to 10:
[1 0 7 3 4]


In [31]:
import numpy as np
print("Vector of length 5 filled with arbitrary integers from 0 to 10:")
x=np.random.randint(0,11,5,'i8')
print("vector1:")
print(x)
y=np.random.randint(0,11,5,'i8')
print("vector2:")
print(y)
print("the multiple of the two vector:")
print(y*x)

Vector of length 5 filled with arbitrary integers from 0 to 10:
vector1:
[10  2  2  3  4]
vector2:
[6 6 4 0 0]
the multiple of the two vector:
[60 12  8  0  0]


In [33]:
import numpy as np
x=np.arange(10,22).reshape(3,4)
print(x)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [35]:
import numpy as np
x=np.arange(10,22).reshape(3,4)
print(x)
print("the size of the matrix:")
print(x.shape)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
the size of the matrix:
(3, 4)


In [37]:
import numpy as np
x=np.eye(3)
print(x)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [39]:
import numpy as np
x=np.zeros((10,10))
for i in range(0,10):
  for w in range(0,10):
    if (i==0 or w==0 or i==9 or w==9):
      x[i][w]=1
       
print(x)       

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [41]:
import numpy as np
x=np.zeros((5,5))
x = np.diag([1, 2, 3, 4, 5])
print(x)       

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [43]:
import numpy as np
x=np.zeros((4,4))
for i in range(0,4):
  for d in range(0,4):
    if (i%2==0 and(d==1 or d==3)):
      x[i][d]=1
    if (i%2!=0 and(d==0 or d==2)):
      x[i][d]=1  
    
print(x)       

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [45]:
import numpy as np
x=np.random.rand(3,3,3)
print(x)       

[[[0.51947832 0.21097242 0.02017855]
  [0.90389744 0.65902539 0.90530304]
  [0.25462473 0.78894277 0.10104961]]

 [[0.76355379 0.37090207 0.02942432]
  [0.99375762 0.45314105 0.30458378]
  [0.31821794 0.30533749 0.78376336]]

 [[0.37844081 0.11114975 0.10825308]
  [0.05916669 0.78237845 0.39110709]
  [0.24577154 0.47341593 0.80352657]]]


In [47]:
import numpy as np
x = np.array([[0, 1], [2, 3]])
print("Original array:")
print(x)
print("sum of each column:")
print(np.sum(x,axis=0))
print("sum of each row:")
print(np.sum(x,axis=1))
print("sum of matrix:")
print(np.sum(x))

Original array:
[[0 1]
 [2 3]]
sum of each column:
[2 4]
sum of each row:
[1 5]
sum of matrix:
6


In [49]:
import numpy as np
x = np.array([4, 5])
y = np.array([7, 10])
print("Original vectors:")
print(x)
print(y)
print("the inner product:")
print(np.dot(x,y))

Original vectors:
[4 5]
[ 7 10]
the inner product:
78


In [51]:
import numpy as np
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 1, 0])
print("Original vector:")
print(v)
print("Original matrix:")
print(m)
print(v+m)

Original vector:
[1 1 0]
Original matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 2  3  3]
 [ 5  6  6]
 [ 8  9  9]
 [11 12 12]]


In [53]:
import numpy as np
m = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
x=np.array(m)
m2=x.tolist()
print(m==m2)


True


In [55]:
import numpy as np
m =np.array([[1, 1, 0, 2],
     [0, 3, 0, 3],
     [1, 0, 4, 4]]) 
print("the original matrix:")
print(m)

for i in range(0,m.shape[0]-1):
  for x in range(0,m.shape[1]):
    if m[i][x]==0:
      m[i+1][x]=0
    s=np.sum(m)
   
print(s)

the original matrix:
[[1 1 0 2]
 [0 3 0 3]
 [1 0 4 4]]
14


In [57]:
import numpy as np
 
nums = np.array ([[3, 2, np.nan, 1],
                 [10, 12, 10, 9],
                 [5, np.nan, 1, np.nan]])
print("Original array:")
print(nums)
print("\nFind the missing data of the said array:")
print(np.isnan(nums)) 

Original array:
[[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]

Find the missing data of the said array:
[[False False  True False]
 [False False False False]
 [False  True False  True]]


In [59]:
import numpy as np
nums1 = np.array([0.5, 1.5, 0.2])
nums2 = np.array([0.4999999999, 1.500000000, 0.2])

np.set_printoptions(precision=15)

print("Original arrays:")
print(nums1)
print(nums2)
print("\nTest said two arrays are equal (element wise) or not:?")
print(nums1 == nums2)
nums1 = np.array([0.5, 1.5, 0.23])
nums2 = np.array([0.4999999999, 1.5000000001, 0.23])
print("\nOriginal arrays:")
np.set_printoptions(precision=15)
print(nums1)
print(nums2)
print("\nTest said two arrays are equal (element wise) or not:?")
print(np.equal(nums1, nums2)) 

Original arrays:
[0.5 1.5 0.2]
[0.4999999999 1.5          0.2         ]

Test said two arrays are equal (element wise) or not:?
[False  True  True]

Original arrays:
[0.5  1.5  0.23]
[0.4999999999 1.5000000001 0.23        ]

Test said two arrays are equal (element wise) or not:?
[False False  True]


In [2]:
import numpy as np
print("the matrix with single digits:")
print(np.arange(0,10))
print("the matrix with two digits:")
print(np.arange(10,100))
print("the matrix with three digits:")
print(np.arange(100,1000))

the matrix with single digits:
[0 1 2 3 4 5 6 7 8 9]
the matrix with two digits:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
the matrix with three digits:
[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207
 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225
 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243
 244 245 246 247 248 249 250 2

In [2]:
import numpy as np
x=np.arange(1,151).reshape(15,10)
print(x)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]
 [101 102 103 104 105 106 107 108 109 110]
 [111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130]
 [131 132 133 134 135 136 137 138 139 140]
 [141 142 143 144 145 146 147 148 149 150]]


In [4]:
import numpy as np  
np.random.seed(10)
print(np.random.rand(40)) 

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335
 0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607
 0.91777412 0.71457578 0.54254437 0.14217005 0.37334076 0.67413362
 0.44183317 0.43401399 0.61776698 0.51313824 0.65039718 0.60103895
 0.8052232  0.52164715 0.90864888 0.31923609 0.09045935 0.30070006
 0.11398436 0.82868133 0.04689632 0.62628715]


In [6]:
import numpy as np 
np.random.seed(20) 
cbrt = np.cbrt(7)
nd1 = 200 
print(cbrt * np.random.randn(10, 4) + nd1)   


[[201.6908267  200.37467631 200.68394275 195.51750123]
 [197.92478992 201.07066048 201.79714021 198.1282331 ]
 [200.96238963 200.77744291 200.61875865 199.05613894]
 [198.48492638 198.38860811 197.55239946 200.47003621]
 [199.91545839 202.99877319 202.01069857 200.77735483]
 [199.67739161 193.89831807 202.14273593 202.54951299]
 [199.53450969 199.7512602  199.79145727 202.97687757]
 [200.24634413 196.04606934 198.30611253 197.88701546]
 [201.78450912 203.94032834 198.21152803 196.91446071]
 [201.0082481  197.03285104 200.63052763 197.82590294]]


In [8]:
import numpy as np 
print("Generate a uniform random sample with replacement:") 
print(np.random.choice(7, 5))
print("\nGenerate a uniform random sample without replacement:") 
print(np.random.choice(7, 5, replace=False))
print("\nGenerate a non-uniform random sample with replacement:") 
print(np.random.choice(7, 5, p=[0.1, 0.2, 0, 0.2, 0.4, 0, 0.1]))
print("\nGenerate a uniform random sample without replacement:") 
print(np.random.choice(7, 5, replace=False, p=[0.1, 0.2, 0, 0.2, 0.4, 0, 0.1]))   

Generate a uniform random sample with replacement:
[2 2 1 5 2]

Generate a uniform random sample without replacement:
[6 3 5 4 2]

Generate a non-uniform random sample with replacement:
[6 1 6 0 1]

Generate a uniform random sample without replacement:
[1 6 4 3 0]


In [10]:
import numpy as np
x=np.random.randint(0,10,size=(4,4))
print(x)
temp=0
for i in range(0,4):
  temp=x[0][i]
  x[0][i]=x[3][i]
  x[3][i]=temp
print("after swapping:")
print(x)

[[6 1 9 6]
 [7 9 7 6]
 [9 8 8 2]
 [2 1 5 2]]
after swapping:
[[2 1 5 2]
 [7 9 7 6]
 [9 8 8 2]
 [6 1 9 6]]


In [12]:
import numpy as np
x=np.zeros((5,6))
print(x)
print(" ")
x[::2,::2]=3
x[1::2,::2]=7
print(x)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
 
[[3. 0. 3. 0. 3. 0.]
 [7. 0. 7. 0. 7. 0.]
 [3. 0. 3. 0. 3. 0.]
 [7. 0. 7. 0. 7. 0.]
 [3. 0. 3. 0. 3. 0.]]


In [14]:
import numpy as np  
print("original array:")
x = np.array([[5.54, 3.38, 7.99],
              [3.54, 4.38, 6.99],
              [1.54, 2.39, 9.29]])
              
print(x)              
              
print("array by sort column:")
print(np.sort(x,axis=0))

print("array by sort row:")
print(np.sort(x,axis=1))
              

original array:
[[5.54 3.38 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]
array by sort column:
[[1.54 2.39 6.99]
 [3.54 3.38 7.99]
 [5.54 4.38 9.29]]
array by sort row:
[[3.38 5.54 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]


In [16]:
import numpy as np  
nums = np.array([[5.54, 3.38, 7.99],
              [3.54, 4.38, 6.99],
              [1.54, 2.39, 9.29]])
print("Original array:")
print(nums)

print("\nElements of the said array greater than", 5)
print(nums[nums > 5])

print("\nElements of the said array less than", 6)
print(nums[nums < 6]) 

Original array:
[[5.54 3.38 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]

Elements of the said array greater than 5
[5.54 7.99 6.99 9.29]

Elements of the said array less than 6
[5.54 3.38 3.54 4.38 1.54 2.39]
